Tywarren/sc 3278/connection monitoring via ping
Ameelio/connect-call-client pull request #13
Opened 2022-04-01 23:47 UTC by jackofsometrade

2022-04-01 23:48 UTC, jackofsometrade commented on src/API.ts
> +  detail?: ParticipantEventDetail;
switching to interface and using optional `?` allows consuming clients to ignore optional `detail`

2022-04-01 23:52 UTC, jackofsometrade commented
Notable things:  

- Hard-coded interval of 500ms (keep in mind this is not HTTP, but websocket)
- Hard-coded TTL of 5 seconds
- Possibility of noisiness if client connection average is near a border between 2 neighboring quality ranges

2022-04-02 00:04 UTC, cainlevy requested changes

2022-04-02 00:04 UTC, cainlevy commented on src/RoomClient.ts
> +  get ConnectionState(): ConnectionState {
camelCase convention for a property:

```suggestion
  get connectionState(): ConnectionState {
```

2022-04-02 00:04 UTC, cainlevy commented on src/RoomClient.ts
> +    this.client.connectionMonitor.emitter.all.clear();
can this be handled by the `stop()` as a private detail?

2022-04-02 00:04 UTC, cainlevy commented on src/ConnectionMonitor.ts
> +      this.socket.on(PONG_EVENT, this.handleResponse);
does CVH need a handler for this? did i miss a PR, or is this some feature of socket.io?

2022-04-02 00:04 UTC, cainlevy commented on src/useConnectCall.ts
> +  };
we should apply `useCallback` here to memoize the function so it's suitable for dependency arrays in the caller

2022-04-02 00:05 UTC, jackofsometrade commented on src/API.ts
> +  detail?: ParticipantEventDetail;
Seems to with our current TS settings.  I didn't dig too deep.

2022-04-02 00:05 UTC, jackofsometrade commented on src/RoomClient.ts
> +    this.client.connectionMonitor.emitter.all.clear();
Yes!  Thanks for that, this was older code that I forgot to update.

2022-04-02 00:08 UTC, jackofsometrade commented on src/ConnectionMonitor.ts
> +      this.socket.on(PONG_EVENT, this.handleResponse);
Yes, there's a PR coming shortly.

2022-04-02 00:08 UTC, jackofsometrade commented on src/useConnectCall.ts
> +  };
Will do

2022-04-02 00:12 UTC, jackofsometrade commented on src/ConnectionMonitor.ts
> +      this.socket.on(PONG_EVENT, this.handleResponse);
https://github.com/Ameelio/connect-video-handler/pull/200

2022-04-02 00:29 UTC, jackofsometrade commented on src/useConnectCall.ts
> +  };
onConnectionState should only be called when there's a change in values anyway, but I like that I learned something new today.

2022-04-04 18:54 UTC, cainlevy approved these changes

2022-04-04 20:36 UTC, merged